services:
  - type: web
    name: editlabel-backend
    env: docker
    plan: free
    branch: main
    dockerfile: ./Dockerfile
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: editlabel_jwt_secret_super_seguro_2026_producao_123456789
      - key: DATABASE_URL
        value: postgresql://postgres:Mudar123@db.exzykikhenrcluinjlna.supabase.co:5432/postgres
      - key: ALLOWED_ORIGINS
        value: https://editlabel-new.vercel.app,https://editlabel-app.vercel.app
